sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t danielvanniekerk/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true danielvanniekerk/docker-react npm run test