name: Docker build and test
on:
  push:
    branches:
      - master
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image and Test
      run: |
        docker build -t danielvanniekerk/docker-react -f Dockerfile.dev .
        docker run -e CI=true danielvanniekerk/docker-react npm run test
        
    - uses: hmanzur/actions-aws-eb@v1.0.0
      with:
        command: 'init docker-react --region eu-west-1 --platform "arn:aws:elasticbeanstalk:eu-west-1::platform/Docker running on 64bit Amazon Linux/2.12.3"'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: "eu-west-1"
        
    - uses: hmanzur/actions-aws-eb@v1.0.0
      with:
        command: 'deploy DockerReact-env'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: "eu-west-1"
