name: Docker build and test
on:
  push:
    branches:
      - master
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
#     - name: Build Docker Image and Test
#       run: |
#         docker build -t danielvanniekerk/docker-react -f Dockerfile.dev .
#         docker run -e CI=true danielvanniekerk/docker-react npm run test
        
#     - uses: hmanzur/actions-aws-eb@v1.0.0
#       with:
#         command: "init docker-react --platform '64bit Amazon Linux 2018.03 v2.16.0 running Docker 19.03.6-ce' --region eu-west-1"
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
#         AWS_DEFAULT_REGION: "eu-west-1"
        
#     - uses: hmanzur/actions-aws-eb@v1.0.0
#       with:
#         command: 'deploy DockerReact-env'
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
#         AWS_DEFAULT_REGION: "eu-west-1"
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: docker-react
        environment_name: DockerReact-env
        version_label: 2
        region: eu-west-1
        deployment_package: deploy.zip
