name: Docker build and test
on:
  push:
    branches:
      - master
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
#     - name: Build Docker Image and Test
#       run: |
#         docker build -t danielvanniekerk/docker-react -f Dockerfile.dev .
#         docker run -e CI=true danielvanniekerk/docker-react npm run test

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: docker-react
        environment_name: DockerReact-env
        version_label: ${{github.run_id}}
        region: eu-west-1
        deployment_package: deploy.zip
