name: Docker build and test
on:
  push:
    branches:
      - master
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image and Test
      run: |
        docker build -t danielvanniekerk/docker-react -f Dockerfile.dev .
        docker run -e CI=true danielvanniekerk/docker-react npm run test
        
    - name: Deploy to AWS Elastic Beanstalk
      uses: Amraneze/aws-beanstalk-deploy@master
      with:
        region: eu-west-1
        environment_name: DockerReact-env
        application_name: docker-react 
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        s3_bucket_name: elasticbeanstalk-eu-west-1-077630070512
        s3_file_path: docker-react
        ebs_version_label: v1
        ebs_wait_for_env_to_be_green: true
        use_same_version: true
        enable_debug: false
